### ISSUE TITLE
data is forced to be lowercase

### ISSUE THREAD

**Issue by JustinAzoff** [csirtgadgets/csirtg-indicator-py#113]
It appears indicator lowercases all strings:

https://github.com/csirtgadgets/csirtg-indicator-py/blob/f283cf9953d6e8aca4e4f8de9b8aa7ca400616f9/csirtg_indicator/indicator.py#L51

This isn't ideal for fields that can contain anything where case matters - passwords, urls, etc.

It looks like 'indicator' itself is skipped from this, but all other fields are affected.

**Comment by wesyoung** [comment]
isn't ideal how?

this was the result of urls and fqdns coming in all sorts of different cases, and instead of forcing the backend to normalize the search, had better luck just down-casing everything to make searching easier.

indicator isn't skipped, it's just taken care of a different way further down the line under the setter.

i could see an argument for something like a username/password under additional data- easy enough to make an exception.

**Comment by JustinAzoff** [comment]
yeah.. I think additional data not being lowercased would almost completely fix this for me, and it looks like it already does that which is why I never noticed this problem before.  I think the main field that is affected is "description".. which I suppose isn't a huge issue, as long as description is never really supposed to be machine readable.
